name: Laravel Package

on:
  workflow_run:
    workflows: ["Laravel Build"]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Download do build
        uses: actions/download-artifact@v4
        with:
          name: laravel-build
          path: codificacao

      - name: Criar ZIP
        run: |
          zip -r laravel-package.zip codificacao \
            -x "codificacao/.env" \
            -x "codificacao/node_modules/*" \
            -x "codificacao/.git/*"

      - name: Upload do pacote final
        uses: actions/upload-artifact@v4
        with:
          name: laravel-empacotado
          path: laravel-package.zip
